export { testSet as basicEdgeAppDirTestSet } from './basicEdgeAppDir';
export { testSet as basicStaticAppDirTestSet } from './basicStaticAppDir';
export { testSet as checkRouteMatchTestSet } from './checkRouteMatch';
export { testSet as configRewritesRedirectsHeadersTestSet } from './configRewritesRedirectsHeaders';
export { testSet as dynamicRoutesTestSet } from './dynamicRoutes';
export { testSet as i18nTestSet } from './i18n';
export { testSet as infiniteLoopTestSet } from './infiniteLoop';
export { testSet as middlewareTestSet } from './middleware';
export { testSet as trailingSlashTestSet } from './trailingSlash';
