/**
 * Metadata generated by the next-on-pages build process.
 */
type NextOnPagesBuildMetadata = {
	/** Locales used by the application (collected from the Vercel output) */
	collectedLocales: string[];
};
