name: Write prerelease comment

on:
  workflow_run:
    workflows: ['Create Pull Request Prerelease']
    types:
      - completed

jobs:
  comment:
    if: ${{ github.repository_owner == 'cloudflare' }}
    runs-on: ubuntu-latest
    name: Write comment to the PR
    steps:
      - name: 'Put PR and workflow ID on the environment'
        uses: actions/github-script@v5
        with:
          script: |
            const allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });

            for (const artifact of allArtifacts.data.artifacts) {
              // Extract the PR number from the artifact name
              const match = /^npm-package-next-on-pages-(\d+)$/.exec(artifact.name);
              if (match) {
                require("fs").appendFileSync(
                  process.env.GITHUB_ENV,
                  `\nWORKFLOW_RUN_PR=${match[1]}` +
                    `\nWORKFLOW_RUN_ID=${context.payload.workflow_run.id}`
                );
                break;
              }
            }

      - name: 'Comment on PR with Link'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ env.WORKFLOW_RUN_PR }}
          message: |
            🧪 A prerelease is available for testing 🧪

            <details>

            You can install this latest build in your project with:

            ```sh
            npm install --save-dev https://prerelease-registry.devprod.cloudflare.dev/next-on-pages/runs/${{ env.WORKFLOW_RUN_ID }}/npm-package-next-on-pages-${{ env.WORKFLOW_RUN_PR }}
            ```

            Or you can immediately run this with `npx`:

            ```sh
            npx https://prerelease-registry.devprod.cloudflare.dev/next-on-pages/runs/${{ env.WORKFLOW_RUN_ID }}/npm-package-next-on-pages-${{ env.WORKFLOW_RUN_PR }}
            ```

            </details>
